### ISSUE TITLE
:bug: [bug] tcp-version : speed and rpm data is weird

### ISSUE THREAD

**Issue by KKWANH** [Shuta-syd/DES02-PiRacer-instrument#54]
The speed data increases until near 2000.

https://github.com/Shuta-syd/DES02-PiRacer-instrument/assets/35485904/77895818-83b9-44bc-890d-f481949a259f

![IMG_6108](https://github.com/Shuta-syd/DES02-PiRacer-instrument/assets/35485904/9e23c7f1-4fbc-401e-8b24-fce61664e2e4)

**Comment by kianwasabi** [comment]
It it because the tcp version uses a different code running on the a arduino. 
Whenever the tcp version is used, the arduino needs to be flashed accordingly using the Arduino code in the tcp branch.
